### ISSUE TITLE
Tab vs Spaces (kuso issue)

### ISSUE THREAD

**Issue by tetsu040e** [ryukana/nogi#1]
It's a matter of taste...

As far as I know, Spaces person is greater than Tab person.
http://www.gizmodo.jp/2016/09/tab-vs-space.html

I'm Spaces person too !
I love 2 Spaces per indent in html case.

Let's become Spaces person !! :)

**Comment by ryukana** [comment]
俺もこれからスペースマンになる！

**Comment by tetsu040e** [comment]
come on!!! :)
